name: build 

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./Dockerfile
          push: true
          registry: ghcr.io
          repository: sklirg/letmein
          tags: latest
          tag_with_sha: true
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
